/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.GerenciaItens;

import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;

import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

import model.Produto;

/**
 *
 * @author caio
 */
public class TelaProdutos extends javax.swing.JInternalFrame {

    GerenciaItens geItens = new GerenciaItens();
    ArrayList<Produto> produtos;
    DefaultTableModel modelo;
    public TelaProdutos() {
        
        initComponents();
        modelo = (DefaultTableModel) tabelaProdutos.getModel();
        tabelaProdutos.setRowSorter(new TableRowSorter(modelo));
        lerTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtxtMarca = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaProdutos = new javax.swing.JTable();
        jtxtModelo = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jbExcluir = new javax.swing.JButton();
        jbSalvar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtxtDescricao = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jtxtpesquisa = new javax.swing.JTextField();
        jbPesquisar = new javax.swing.JButton();
        jbprimeiro = new javax.swing.JButton();
        jbanterior = new javax.swing.JButton();
        jbproximo = new javax.swing.JButton();
        jbultimo = new javax.swing.JButton();
        jbLimpar = new javax.swing.JButton();
        jbCriar = new javax.swing.JButton();
        jtxtValidade = new javax.swing.JFormattedTextField();
        jtxPreco = new javax.swing.JTextField();
        jtxtCodigo = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jtxtId = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setIconifiable(true);
        setResizable(true);
        setTitle("Produtos");

        jtxtMarca.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtxtMarcaFocusLost(evt);
            }
        });

        jLabel4.setText("Validade");

        jLabel5.setText("Modelo");

        tabelaProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id_cadastro", "Código Fab", "Descrição", "Preço", "Validade", "Marca", "modelo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Float.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaProdutos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaProdutosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelaProdutos);

        jtxtModelo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtxtModeloFocusLost(evt);
            }
        });

        jLabel6.setText("Preço");

        jbExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/delete_remove_page_document_16678.png"))); // NOI18N
        jbExcluir.setText("Excluir");
        jbExcluir.setEnabled(false);
        jbExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbExcluirActionPerformed(evt);
            }
        });

        jbSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/save_3621.png"))); // NOI18N
        jbSalvar.setText("Salvar");
        jbSalvar.setEnabled(false);
        jbSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalvarActionPerformed(evt);
            }
        });

        jLabel1.setText("Código Fab");

        jLabel2.setText("Descrição");

        jtxtDescricao.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtxtDescricaoFocusLost(evt);
            }
        });

        jLabel3.setText("Marca");

        jLabel7.setText("Pesquisar");

        jtxtpesquisa.setText("Insira o código do produto");
        jtxtpesquisa.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtpesquisaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtxtpesquisaFocusLost(evt);
            }
        });
        jtxtpesquisa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtxtpesquisaMouseClicked(evt);
            }
        });
        jtxtpesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtpesquisaActionPerformed(evt);
            }
        });

        jbPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pesquisa.png"))); // NOI18N
        jbPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPesquisarActionPerformed(evt);
            }
        });

        jbprimeiro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/ir_primeiro.png"))); // NOI18N
        jbprimeiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbprimeiroActionPerformed(evt);
            }
        });

        jbanterior.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/anterior.png"))); // NOI18N
        jbanterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbanteriorActionPerformed(evt);
            }
        });

        jbproximo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/nav_proximo.png"))); // NOI18N
        jbproximo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbproximoActionPerformed(evt);
            }
        });

        jbultimo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/ir_ultimo.png"))); // NOI18N
        jbultimo.setToolTipText("");
        jbultimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbultimoActionPerformed(evt);
            }
        });

        jbLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/new_page_document_16676.png"))); // NOI18N
        jbLimpar.setText("Novo");
        jbLimpar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jbLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLimparActionPerformed(evt);
            }
        });

        jbCriar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/accept_ok_database_16695.png"))); // NOI18N
        jbCriar.setText("Criar");
        jbCriar.setEnabled(false);
        jbCriar.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jbCriarItemStateChanged(evt);
            }
        });
        jbCriar.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jbCriarStateChanged(evt);
            }
        });
        jbCriar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCriarActionPerformed(evt);
            }
        });

        try {
            jtxtValidade.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jtxtValidade.setToolTipText("");

        jtxPreco.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtxPrecoFocusLost(evt);
            }
        });

        jLabel8.setText("Id");

        jtxtId.setEditable(false);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/DocumentEdit_40924.png"))); // NOI18N
        jButton1.setText("Editar");
        jButton1.setEnabled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(12, 12, 12)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jtxtId, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(12, 12, 12)
                                            .addComponent(jtxtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(117, 117, 117)
                                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(0, 0, Short.MAX_VALUE))
                                        .addComponent(jtxtDescricao)))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 900, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jbprimeiro, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(6, 6, 6)
                                            .addComponent(jbanterior, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jbproximo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jbultimo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(362, 362, 362)
                                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(12, 12, 12)
                                            .addComponent(jtxtpesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(6, 6, 6)
                                            .addComponent(jbPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(132, 132, 132)
                                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jtxtValidade, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(12, 12, 12)
                                            .addComponent(jtxPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(258, 258, 258)
                                            .addComponent(jbCriar, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jbExcluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addGap(0, 0, Short.MAX_VALUE))))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(12, 12, 12)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(jtxtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(26, 26, 26)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jtxtModelo)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jbLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jbSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGap(0, 0, Short.MAX_VALUE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1)))
                .addGap(12, 12, 12))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbprimeiro, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbanterior, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbproximo, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbultimo, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jtxtpesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jbPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtxtId, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jtxtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jtxtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtxtValidade, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jtxPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jbSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jbLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jbCriar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jbExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tabelaProdutosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaProdutosMouseClicked
        setarCampos();
        jButton1.setEnabled(true);
    }//GEN-LAST:event_tabelaProdutosMouseClicked
    public void setarCampos() {
       
            int setar = tabelaProdutos.getSelectedRow();
            jtxtId.setText(tabelaProdutos.getValueAt(setar, 0).toString());
            jtxtCodigo.setText(tabelaProdutos.getValueAt(setar, 1).toString());
            jtxtDescricao.setText(tabelaProdutos.getValueAt(setar, 2).toString());
            jtxPreco.setText(tabelaProdutos.getValueAt(setar, 3).toString());
            jtxtValidade.setText(tabelaProdutos.getValueAt(setar, 4).toString());
            jtxtMarca.setText(tabelaProdutos.getValueAt(setar, 5).toString());
            jtxtModelo.setText(tabelaProdutos.getValueAt(setar, 6).toString());
            jbCriar.setEnabled(false);
            jtxtCodigo.setEditable(false);
            jbExcluir.setEnabled(true);
            desabilitarEditarCampos();
            
                    
    }
    public void desabilitarEditarCampos(){
     jtxPreco.setEditable(false);
        jtxtDescricao.setEditable(false);
        jtxtMarca.setEditable(false);
        jtxtValidade.setEditable(false);
        jtxtModelo.setEditable(false);   
    }
    public void habilitarEditarCampos(){
        jtxPreco.setEditable(true);
        jtxtDescricao.setEditable(true);
        jtxtMarca.setEditable(true);
        jtxtValidade.setEditable(true);
        jtxtModelo.setEditable(true);
    }
    private void lerTabela() {
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        DefaultTableModel modelo = (DefaultTableModel) tabelaProdutos.getModel();
        produtos = geItens.listarProdutos();
        
        for (Produto p : produtos) {
           
                    
            modelo.addRow(new Object[]{
                p.getId(),
                p.getCodProduto(),
                p.getDescricao(),
                p.getPreco(),
                p.getValidade().format(formatter),
                p.getMarca(),
                p.getModelo()
     
            });
        }

    }
    
    
    private void jbExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbExcluirActionPerformed
       if(JOptionPane.showConfirmDialog(null, jtxtCodigo.getText(), "Confirmar exclusão", JOptionPane.YES_NO_OPTION) == 0){
           geItens.excluirProduto(Integer.parseInt(jtxtId.getText()));
           int x = tabelaProdutos.getSelectedRow();
           modelo.removeRow(tabelaProdutos.getSelectedRow());
           JOptionPane.showMessageDialog(null, "Excluido");
       }
    }//GEN-LAST:event_jbExcluirActionPerformed

    private void jbSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalvarActionPerformed
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        Produto p = new Produto();
        p.setDescricao(jtxtDescricao.getText());
        p.setMarca(jtxtMarca.getText());
        p.setModelo(jtxtModelo.getText());
        p.setPreco(Float.parseFloat(jtxPreco.getText()));
        p.setValidade(LocalDate.parse(jtxtValidade.getText(), formatter));
        p.setCodProduto(jtxtCodigo.getText());
        p.setId(Integer.parseInt(jtxtId.getText()));
        geItens.alterarProdutos(p);
        
        int x = tabelaProdutos.getSelectedRow();
        tabelaProdutos.setValueAt(jtxtDescricao.getText(), x, 2);
        tabelaProdutos.setValueAt(Float.parseFloat(jtxPreco.getText()), x, 3);
        tabelaProdutos.setValueAt(jtxtValidade.getText(), x, 4);
        tabelaProdutos.setValueAt(jtxtMarca.getText(), x, 5);
        tabelaProdutos.setValueAt(jtxtModelo.getText(), x, 6);
        JOptionPane.showMessageDialog(null, "Alterado com sucesso");
        jbSalvar.setEnabled(false);
        
        
    }//GEN-LAST:event_jbSalvarActionPerformed

    private void jtxtpesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtpesquisaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtpesquisaActionPerformed

    private void jtxtpesquisaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxtpesquisaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtpesquisaMouseClicked

    private void jtxtpesquisaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtpesquisaFocusGained
       if(jtxtpesquisa.getText().equals("Insira o código do produto"))
           jtxtpesquisa.setText("");
       else
           jtxtpesquisa.selectAll();
    }//GEN-LAST:event_jtxtpesquisaFocusGained

    private void jtxtpesquisaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtpesquisaFocusLost
        if(jtxtpesquisa.getText().isEmpty())
            jtxtpesquisa.setText("Insira o código do produto");
    }//GEN-LAST:event_jtxtpesquisaFocusLost

    public void limpaCampos(){
        jtxtCodigo.setText("");
        jtxtDescricao.setText("");
        jtxtMarca.setText("");
        jtxtModelo.setText("");
        jtxtValidade.setText("");
        jtxPreco.setText("");
    }
    public void proximoCod(){
         jtxtId.setText(new String(""+ geItens.proximoCodigo()));
    }
    
        
    private void jbLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLimparActionPerformed
        limpaCampos();
        proximoCod();
        //jbSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/criar.png")));
        //jbCriar.setEnabled(true);
        jbSalvar.setEnabled(false);
        jtxtCodigo.setEditable(true);
        jButton1.setEnabled(false);
    }//GEN-LAST:event_jbLimparActionPerformed

    private void jbCriarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCriarActionPerformed
       DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy");
       Produto p = new Produto();
       p.setCodProduto(jtxtCodigo.getText());
       p.setDescricao(jtxtDescricao.getText());
       p.setId(WIDTH);
       p.setMarca(jtxtMarca.getText());
       p.setModelo(jtxtModelo.getText());
       p.setPreco(Float.parseFloat(jtxPreco.getText()));
       p.setValidade(LocalDate.parse(jtxtValidade.getText(), formatter));
       geItens.cadastrarProduto(p);
       JOptionPane.showMessageDialog(this,"Produto Cadastrado");
       DefaultTableModel modelo = (DefaultTableModel) tabelaProdutos.getModel();
       modelo.addRow(new Object[]{
                (geItens.proximoCodigo() -1),
                jtxtCodigo.getText(),
                jtxtDescricao.getText(),
                Float.parseFloat(jtxPreco.getText()),
                jtxtValidade.getText(),
                jtxtMarca.getText(),
                jtxtModelo.getText()
     
            });
            limpaCampos();
            proximoCod();
        jbCriar.setEnabled(false);
        
        
        
        
    }//GEN-LAST:event_jbCriarActionPerformed
    public boolean preencheu(){
        if(!jtxtCodigo.getText().isEmpty() &&
                !jtxtDescricao.getText().isEmpty() &&
                !jtxPreco.getText().isEmpty() &&
                !jtxtValidade.getText().equals("  /  /    ")&&
                !jtxtMarca.getText().isEmpty() &&
                !jtxtModelo.getText().isEmpty()){
                return true;
        }
        return false;
    }
    private void jbCriarStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jbCriarStateChanged
       
    }//GEN-LAST:event_jbCriarStateChanged

    private void jbCriarItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jbCriarItemStateChanged
       
    }//GEN-LAST:event_jbCriarItemStateChanged

    private void jtxtDescricaoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtDescricaoFocusLost
        if(preencheu() && jtxtCodigo.isEditable()){
            jbCriar.setEnabled(true);
        }else{
          jbCriar.setEnabled(false); 
       }
    }//GEN-LAST:event_jtxtDescricaoFocusLost

    private void jtxtMarcaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtMarcaFocusLost
        if(preencheu() && jtxtCodigo.isEditable()){
            jbCriar.setEnabled(true);
        }else{
          jbCriar.setEnabled(false); 
       }
    }//GEN-LAST:event_jtxtMarcaFocusLost

    private void jtxtModeloFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtModeloFocusLost
       if(preencheu() && jtxtCodigo.isEditable()){
            jbCriar.setEnabled(true);
        }else{
          jbCriar.setEnabled(false); 
       }
    }//GEN-LAST:event_jtxtModeloFocusLost

    private void jbPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPesquisarActionPerformed
        if (jtxtpesquisa.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Insira um código pra pesquisa");
        } else {
            for (int x = 0; x < tabelaProdutos.getRowCount(); x++) {
                if (jtxtpesquisa.getText().equals(tabelaProdutos.getValueAt(x, 0).toString())) {
                    tabelaProdutos.clearSelection();
                    tabelaProdutos.addRowSelectionInterval(x, x);
                    setarCampos();
                    return;
                }
            }
            JOptionPane.showMessageDialog(this, "Pesquisa não encontrou resultados");
        }
        
    }//GEN-LAST:event_jbPesquisarActionPerformed

    private void jbprimeiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbprimeiroActionPerformed
        
        tabelaProdutos.clearSelection();
        int p = produtos.get(0).getId();
        tabelaProdutos.addRowSelectionInterval(0, 0);
        setarCampos();
    }//GEN-LAST:event_jbprimeiroActionPerformed

    private void jbultimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbultimoActionPerformed
        tabelaProdutos.clearSelection();
        int x = tabelaProdutos.getRowCount();
        tabelaProdutos.addRowSelectionInterval(x-1, x-1);
        setarCampos();
    }//GEN-LAST:event_jbultimoActionPerformed

    private void jbanteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbanteriorActionPerformed

        int x = tabelaProdutos.getSelectedRow() -1;
        if(x>=0){
        tabelaProdutos.clearSelection();
        tabelaProdutos.addRowSelectionInterval(x, x);
        setarCampos();}
    }//GEN-LAST:event_jbanteriorActionPerformed

    private void jbproximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbproximoActionPerformed
       
        int x = tabelaProdutos.getSelectedRow() +1;
        if(x<tabelaProdutos.getRowCount()){
        tabelaProdutos.clearSelection();
        tabelaProdutos.addRowSelectionInterval(x, x);
        setarCampos();}
    }//GEN-LAST:event_jbproximoActionPerformed

    private void jtxPrecoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxPrecoFocusLost
        if(preencheu() && jtxtCodigo.isEditable()){
            jbCriar.setEnabled(true);
        }else{
          jbCriar.setEnabled(false); 
       }
    }//GEN-LAST:event_jtxPrecoFocusLost

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        habilitarEditarCampos();
        jbSalvar.setEnabled(true);
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbCriar;
    private javax.swing.JButton jbExcluir;
    private javax.swing.JButton jbLimpar;
    private javax.swing.JButton jbPesquisar;
    private javax.swing.JButton jbSalvar;
    private javax.swing.JButton jbanterior;
    private javax.swing.JButton jbprimeiro;
    private javax.swing.JButton jbproximo;
    private javax.swing.JButton jbultimo;
    private javax.swing.JTextField jtxPreco;
    private javax.swing.JTextField jtxtCodigo;
    private javax.swing.JTextField jtxtDescricao;
    private javax.swing.JTextField jtxtId;
    private javax.swing.JTextField jtxtMarca;
    private javax.swing.JTextField jtxtModelo;
    private javax.swing.JFormattedTextField jtxtValidade;
    private javax.swing.JTextField jtxtpesquisa;
    private javax.swing.JTable tabelaProdutos;
    // End of variables declaration//GEN-END:variables
}
